name: Run pytest for functionality testing

on:
  push:
    branches:
      - main
      - add-tests
  pull_request:
    branches:
      - main
      - add-tests

jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # or the version you use

    - name: Install dependencies
      run: |
        pip install -r requirements-test.txt
    
    - name: Run tests
      run: |
        pytest --cov=napari_dmc_brainmap test
