name: Run pytest for functionality testing

on:
  push:
    branches:
      - main  # Run tests on commits to the main branch; change this if needed
  pull_request:
    branches:
      - main  # Run tests on pull requests targeting the main branch

jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # or the version you use

    - name: Install dependencies
      run: |
        pip install -r requirements-test.txt
    
    - name: Run tests
      run: |
        xvfb-run pytest
